### ISSUE TITLE
Corrections on admiralty ships

### ISSUE THREAD

**Issue by tanareed** [intrinsical/sto-aso#1]
Admiralty Card Screenshot: 
![sto_ass_jh_vancarr](https://user-images.githubusercontent.com/16707513/45936688-4b927f80-bf6e-11e8-98bf-3a9b9353950d.png)

Ship Name: Jem'Hadar Vanguard Carrier
Ship Type: SCI
Rarity: Very Rare
Tier: T6
ENG: 20
SCI: 63
TAC: 34
Ability: 2.5x Critical Rating from SCI
(This currently has SCI and TAC flipped in ASO.)

Admiralty Card Screenshot: 
![sto_ass_jh_vanraid](https://user-images.githubusercontent.com/16707513/45936740-d7a4a700-bf6e-11e8-9c4a-3c088b699fa0.png)

Ship Name: Jem'Hadar Vanguard Heavy Raider
Ship Type: TAC
Rarity: Very Rare
Tier: T6
ENG: 30
SCI: 40
TAC: 47
Ability: Ignores +/- TAC from Events
(This currently has stats of 30/20/47 in ASO.)

Admiralty Card Screenshot: 
![sto_ass_jhdc_t5](https://user-images.githubusercontent.com/16707513/45938333-daf35f00-bf7d-11e8-98e2-ae5ddb58717b.png)

Ship Name: Jem'Hadar Dreadnought Carrier
Ship Type: TAC
Rarity: Ultra Rare
Tier: T5
ENG: 44
SCI: 16
TAC: 45
Ability: +8 ENG per SciShip or TacShip
(This is currently listed as an ENG card; it should be TAC.)

**Comment by tanareed** [comment]
I've made these changes and a few others (mostly rarity fixes) on the branch [here](https://github.com/intrinsical/sto-aso/commit/bd7241c81d9a9ab425376280015dcabe077a0a84). Github would not take a submission without fixing the character used in "Minority - Majority", though, so it has changes there. Please take a look.

**Comment by intrinsical** [comment]
I have seen it last week. Thank you for the submission. I'm leaving it open for now because I'm working on adding icons for all ships. 

Once that is done, I will be adding all the new ships as well as any changes to ship stats all together in one shot before pushing out a new release.

**Comment by intrinsical** [comment]
The changes have been rolled into v1.0.30
