### ISSUE TITLE
Lukari Ho'kuun card screenshot

### ISSUE THREAD

**Issue by BreakingForce** [intrinsical/sto-aso#10]
Not a new admiralty ship, but the app does not have a picture for the Lukari Ho'kuun Science Vessel, so I thought I'd send one: 
![lukari ho kuun science vessel admiralty card](https://user-images.githubusercontent.com/47827621/53120501-fc9e4580-351f-11e9-8b08-34dd9185a8a0.png)

**Comment by intrinsical** [comment]
There is an icon for the Lukari Ho'kuun.
