### ISSUE TITLE
Bajoran Interceptor card screenshot

### ISSUE THREAD

**Issue by BreakingForce** [intrinsical/sto-aso#11]
Not a new admiralty ship, but the app does not have a picture for the Bajoran Interceptor, so here's one.
![bajoran interceptor admiralty card](https://user-images.githubusercontent.com/47827621/53120792-a1b91e00-3520-11e9-9223-45a09a38879b.png)

**Comment by intrinsical** [comment]
There is an icon for the Bajoran Interceptor.
