### ISSUE TITLE
Type 7 Shuttle card screenshot

### ISSUE THREAD

**Issue by BreakingForce** [intrinsical/sto-aso#12]
Not a new admiralty ship, but the app does not have a picture for the Type 7 Shuttle, so here's one. 
![type 7 shuttle admiralty card](https://user-images.githubusercontent.com/47827621/53121039-43d90600-3521-11e9-9500-e3e790e78d90.png)

**Comment by intrinsical** [comment]
There is an icon for the Type 7 Shuttle.
