### ISSUE TITLE
Phoenix Replica Smallcraft card screenshot

### ISSUE THREAD

**Issue by BreakingForce** [intrinsical/sto-aso#13]
Not a new admiralty ship, but the app does not have a picture for the Phoenix Replica Smallcraft, so here's one: 
![phoenix replica smallcraft admiralty card](https://user-images.githubusercontent.com/47827621/53121319-f0b38300-3521-11e9-8cb4-ecb45097eecf.png)

**Comment by intrinsical** [comment]
There is an icon for the Phoenix.
