### ISSUE TITLE
Fed Shuttlecraft, Malachowski Light Cruiser, Prototype Walker stats

### ISSUE THREAD

**Issue by tanareed** [intrinsical/sto-aso#3]
Admiralty Card Screenshot: 
![sto_ass_walker_t4](https://user-images.githubusercontent.com/16707513/48278188-ac342980-e401-11e8-8010-70626ce124fb.png)

Ship Name: Prototype Light Exploration Cruiser
Ship Type: ENG
Rarity: Common (I suspect this is a bug. The stat total and that it's a C-Store ship both point at it being Rare, but the card is a Common.)
Tier: T4
ENG: 44
SCI: 14
TAC: 14
Ability: +10 ENG per EngShip

Admiralty Card Screenshot: 
![sto_ass_malachowski_t1](https://user-images.githubusercontent.com/16707513/48278181-a50d1b80-e401-11e8-84b1-1e86c85ba31c.png)

Ship Name: Malachowski Light Cruiser
Ship Type: ENG
Rarity: Common
Tier: T1
ENG: 6
SCI: 5
TAC: 4
Ability: 2x Critical Rating from Events

Admiralty Card Screenshot: 
![sto_ass_fedshuttle_ts](https://user-images.githubusercontent.com/16707513/48278199-b2c2a100-e401-11e8-9611-42a410d771b7.png)

Ship Name: Federation Shuttlecraft
Ship Type: N/A
Rarity: Common
Tier: Small Craft
ENG: 2
SCI: 2
TAC: 2
Ability: -25% Maintenance per ANY Ship (Not Small Craft)

**Comment by intrinsical** [comment]
Thank you for the ship stats! They have been rolled into v1.0.30
