### ISSUE TITLE
New admiralty ship

### ISSUE THREAD

**Issue by MjrTom** [intrinsical/sto-aso#5]
Admiralty Card Screenshot: 
![fekihri warship](https://user-images.githubusercontent.com/1137977/51082143-07ff8500-16c7-11e9-9962-cdab009bfd7a.png)

Ship Name: Fek'Ihri Warship (T6)
Ship Type: TAC
Rarity: Ultra Rare
Tier: T6
ENG: 30
SCI: 33
TAC: 63
Ability: +10 SCI per TacShip

**Comment by MjrTom** [comment]
"Fek'Ihri S'torr Warship [T6]" is not called "Fek'Ihri S'torr Warship [T6]" ...  it is called 'Fek'Ihri Warship (T6)' and the information is *right here*

**Comment by intrinsical** [comment]
Ship added and will be in the next release
