### ISSUE TITLE
Typo in ship name: Caitian Atrox Carrier

### ISSUE THREAD

**Issue by tanareed** [intrinsical/sto-aso#6]
Admiralty Card Screenshot: 
![sto_ass_atrox_t5](https://user-images.githubusercontent.com/16707513/51431838-84242c00-1be3-11e9-94fb-66590d56d682.png)

Ship Name: Caitian Atrox Carrier
Ship Type: SCI
Rarity: Rare
Tier: T5
ENG: 26
SCI: 50
TAC: 14
Ability: +20 SCI and TAC when Alone

Basically, there's a missing "i" in the ship's name in ASO. The Fleet version does not appear to be affected.

**Comment by intrinsical** [comment]
Fixed
